apiVersion: v1
kind: Pod
metadata:
  name: burstableapp
  labels:
    app: devone

spec:
  containers:
    - name: boxone
      image: docker.io/lovelearnlinux/webserver:v1
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      
---

apiVersion: v1
kind: Pod
metadata:
  name: guaranteedapp
  labels:
    app: devone

spec:
  containers:
    - name: boxone
      image: docker.io/lovelearnlinux/webserver:v1
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 500Mi
